# This file automatically generated by
#    /Users/couchbase/jenkins/workspace/python/sdk/python-packaging-pipeline/py-client/./couchbase_version.py
# at
#    2023-08-08 09:28:36.725880
__version__ = '4.1.7rc1'