# Generated by Django 4.2 on 2023-07-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_silly_stripe', '0010_alter_subscription_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
