
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-05T15:38:16-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "5fb1b0708e5e5633cb608de06176145ac57d9c90",
 "version": "0.0.2-rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
