# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pysandwich/proto/api/v1/certificate.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pysandwich.proto.api.v1 import data_source_pb2 as pysandwich_dot_proto_dot_api_dot_v1_dot_data__source__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)pysandwich/proto/api/v1/certificate.proto\x12\x19saq.sandwich.proto.api.v1\x1a)pysandwich/proto/api/v1/data_source.proto\"T\n\x0b\x43\x65rtificate\x12;\n\x06static\x18\x01 \x01(\x0b\x32).saq.sandwich.proto.api.v1.ASN1DataSourceH\x00\x42\x08\n\x06sourceB>Z<github.com/sandbox-quantum/sandwich/go/proto/sandwich/api/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pysandwich.proto.api.v1.certificate_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z<github.com/sandbox-quantum/sandwich/go/proto/sandwich/api/v1'
  _globals['_CERTIFICATE']._serialized_start=115
  _globals['_CERTIFICATE']._serialized_end=199
# @@protoc_insertion_point(module_scope)
