# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pysandwich/proto/api/v1/compliance.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(pysandwich/proto/api/v1/compliance.proto\x12\x19saq.sandwich.proto.api.v1\"\xbb\x02\n\nCompliance\x12\x42\n\rhybrid_choice\x18\x01 \x01(\x0e\x32+.saq.sandwich.proto.api.v1.HybridAlgoChoice\x12M\n\x13quantum_safe_choice\x18\x02 \x01(\x0e\x32\x30.saq.sandwich.proto.api.v1.QuantumSafeAlgoChoice\x12H\n\x10\x63lassical_choice\x18\x03 \x01(\x0e\x32..saq.sandwich.proto.api.v1.ClassicalAlgoChoice\x12P\n\x13\x62it_strength_choice\x18\x04 \x01(\x0e\x32\x33.saq.sandwich.proto.api.v1.NISTSecurityStrengthBits*V\n\x13\x43lassicalAlgoChoice\x12\x1f\n\x1b\x43LASSICAL_ALGORITHMS_FORBID\x10\x00\x12\x1e\n\x1a\x43LASSICAL_ALGORITHMS_ALLOW\x10\x01*^\n\x15QuantumSafeAlgoChoice\x12!\n\x1dQUANTUM_SAFE_ALGORITHMS_ALLOW\x10\x00\x12\"\n\x1eQUANTUM_SAFE_ALGORITHMS_FORBID\x10\x01*M\n\x10HybridAlgoChoice\x12\x1b\n\x17HYBRID_ALGORITHMS_ALLOW\x10\x00\x12\x1c\n\x18HYBRID_ALGORITHMS_FORBID\x10\x01*w\n\x18NISTSecurityStrengthBits\x12\x1d\n\x19\x42IT_STRENGTH_AT_LEAST_128\x10\x00\x12\x1d\n\x19\x42IT_STRENGTH_AT_LEAST_192\x10\x01\x12\x1d\n\x19\x42IT_STRENGTH_AT_LEAST_256\x10\x02\x42>Z<github.com/sandbox-quantum/sandwich/go/proto/sandwich/api/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pysandwich.proto.api.v1.compliance_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z<github.com/sandbox-quantum/sandwich/go/proto/sandwich/api/v1'
  _globals['_CLASSICALALGOCHOICE']._serialized_start=389
  _globals['_CLASSICALALGOCHOICE']._serialized_end=475
  _globals['_QUANTUMSAFEALGOCHOICE']._serialized_start=477
  _globals['_QUANTUMSAFEALGOCHOICE']._serialized_end=571
  _globals['_HYBRIDALGOCHOICE']._serialized_start=573
  _globals['_HYBRIDALGOCHOICE']._serialized_end=650
  _globals['_NISTSECURITYSTRENGTHBITS']._serialized_start=652
  _globals['_NISTSECURITYSTRENGTHBITS']._serialized_end=771
  _globals['_COMPLIANCE']._serialized_start=72
  _globals['_COMPLIANCE']._serialized_end=387
# @@protoc_insertion_point(module_scope)
