# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pysandwich/proto/api/v1/configuration.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pysandwich.proto.api.v1 import compliance_pb2 as pysandwich_dot_proto_dot_api_dot_v1_dot_compliance__pb2
from pysandwich.proto.api.v1 import tls_pb2 as pysandwich_dot_proto_dot_api_dot_v1_dot_tls__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+pysandwich/proto/api/v1/configuration.proto\x12\x19saq.sandwich.proto.api.v1\x1a(pysandwich/proto/api/v1/compliance.proto\x1a!pysandwich/proto/api/v1/tls.proto\"S\n\rClientOptions\x12:\n\x03tls\x18\x01 \x01(\x0b\x32+.saq.sandwich.proto.api.v1.TLSClientOptionsH\x00\x42\x06\n\x04opts\"S\n\rServerOptions\x12:\n\x03tls\x18\x01 \x01(\x0b\x32+.saq.sandwich.proto.api.v1.TLSServerOptionsH\x00\x42\x06\n\x04opts\"\x83\x02\n\rConfiguration\x12\x37\n\x04impl\x18\x01 \x01(\x0e\x32).saq.sandwich.proto.api.v1.Implementation\x12:\n\x06\x63lient\x18\x02 \x01(\x0b\x32(.saq.sandwich.proto.api.v1.ClientOptionsH\x00\x12:\n\x06server\x18\x03 \x01(\x0b\x32(.saq.sandwich.proto.api.v1.ServerOptionsH\x00\x12\x39\n\ncompliance\x18\x04 \x01(\x0b\x32%.saq.sandwich.proto.api.v1.ComplianceB\x06\n\x04opts*Y\n\x0eImplementation\x12\x14\n\x10IMPL_UNSPECIFIED\x10\x00\x12\x19\n\x15IMPL_OPENSSL1_1_1_OQS\x10\x01\x12\x16\n\x12IMPL_BORINGSSL_OQS\x10\x02\x42>Z<github.com/sandbox-quantum/sandwich/go/proto/sandwich/api/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pysandwich.proto.api.v1.configuration_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z<github.com/sandbox-quantum/sandwich/go/proto/sandwich/api/v1'
  _globals['_IMPLEMENTATION']._serialized_start=583
  _globals['_IMPLEMENTATION']._serialized_end=672
  _globals['_CLIENTOPTIONS']._serialized_start=151
  _globals['_CLIENTOPTIONS']._serialized_end=234
  _globals['_SERVEROPTIONS']._serialized_start=236
  _globals['_SERVEROPTIONS']._serialized_end=319
  _globals['_CONFIGURATION']._serialized_start=322
  _globals['_CONFIGURATION']._serialized_end=581
# @@protoc_insertion_point(module_scope)
