# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pysandwich/proto/api/v1/verifiers.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pysandwich.proto.api.v1 import certificate_pb2 as pysandwich_dot_proto_dot_api_dot_v1_dot_certificate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'pysandwich/proto/api/v1/verifiers.proto\x12\x19saq.sandwich.proto.api.v1\x1a)pysandwich/proto/api/v1/certificate.proto\"\x0f\n\rEmptyVerifier\"\x88\x01\n\x0cX509Verifier\x12;\n\x0btrusted_cas\x18\x01 \x03(\x0b\x32&.saq.sandwich.proto.api.v1.Certificate\x12!\n\x19\x61llow_expired_certificate\x18\x04 \x01(\x08\x12\x18\n\x10max_verify_depth\x18\x05 \x01(\r\"I\n\nSANMatcher\x12\x0f\n\x05\x65mail\x18\x01 \x01(\tH\x00\x12\r\n\x03\x64ns\x18\x02 \x01(\tH\x00\x12\x14\n\nip_address\x18\x03 \x01(\tH\x00\x42\x05\n\x03san\"G\n\x0bSANVerifier\x12\x38\n\talt_names\x18\x01 \x03(\x0b\x32%.saq.sandwich.proto.api.v1.SANMatcher\"\xa0\x01\n\x0eTunnelVerifier\x12>\n\x0csan_verifier\x18\x01 \x01(\x0b\x32&.saq.sandwich.proto.api.v1.SANVerifierH\x00\x12\x42\n\x0e\x65mpty_verifier\x18\x02 \x01(\x0b\x32(.saq.sandwich.proto.api.v1.EmptyVerifierH\x00\x42\n\n\x08verifierB>Z<github.com/sandbox-quantum/sandwich/go/proto/sandwich/api/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pysandwich.proto.api.v1.verifiers_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z<github.com/sandbox-quantum/sandwich/go/proto/sandwich/api/v1'
  _globals['_EMPTYVERIFIER']._serialized_start=113
  _globals['_EMPTYVERIFIER']._serialized_end=128
  _globals['_X509VERIFIER']._serialized_start=131
  _globals['_X509VERIFIER']._serialized_end=267
  _globals['_SANMATCHER']._serialized_start=269
  _globals['_SANMATCHER']._serialized_end=342
  _globals['_SANVERIFIER']._serialized_start=344
  _globals['_SANVERIFIER']._serialized_end=415
  _globals['_TUNNELVERIFIER']._serialized_start=418
  _globals['_TUNNELVERIFIER']._serialized_end=578
# @@protoc_insertion_point(module_scope)
