
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-07T10:16:54+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0c6c78df89074802c005dad6cdd451973e005937",
 "version": "0.8.0.post.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
