
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-06T12:44:47+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4087ceab158e77546b8b8a1d12355d2b80d12d51",
 "version": "2.0.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
