# This file automatically generated by
#    /home/couchbase/jenkins/workspace/python/sdk/python-packaging-pipeline/py-client/couchbase_version.py
# at
#    2023-08-08 16:30:19.320240
__version__ = '4.1.7rc1'