#!/usr/bin/env python

from setuptools import setup, find_packages

setup(
    name="PySmartShell",
    version="0.0.5",
    description="PySmartShell is a quick context creator provider for command creation",
    python_requires=">3.10.0",
    author="Colageo Mirko",
    author_email="mirko.colageo@gmail.com",
    install_requires=[
        "bleach==5.0.1",
        "certifi==2022.9.24",
        "cffi==1.15.1",
        "charset-normalizer==2.1.1",
        "commonmark==0.9.1",
        "cryptography==38.0.1",
        "decorator==5.1.1",
        "docutils==0.19",
        "idna==3.4",
        "importlib-metadata==5.0.0",
        "jaraco.classes==3.2.3",
        "jeepney==0.8.0",
        "keyring==23.9.3",
        "more-itertools==9.0.0",
        "numpy==1.23.4",
        "pandas==1.5.1",
        "pkginfo==1.8.3",
        "pycparser==2.21",
        "Pygments==2.13.0",
        "python-dateutil==2.8.2",
        "pytz==2022.6",
        "readme-renderer==37.3",
        "requests==2.28.1",
        "requests-toolbelt==0.10.1",
        "rfc3986==2.0.0",
        "rich==12.6.0",
        "SecretStorage==3.3.3",
        "six==1.16.0",
        "urllib3==1.26.12",
        "validators==0.20.0",
        "webencodings==0.5.1",
        "zipp==3.10.0",
    ],
    package_dir={"": "src"},
    packages=find_packages("src"),
)
