# Generated by Django 4.2.1 on 2023-05-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IBConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.GenericIPAddressField(default='127.0.0.1')),
                ('port', models.IntegerField(default=7497)),
                ('ClientID', models.IntegerField(default=0)),
                ('LogLevel', models.IntegerField(default=5)),
                ('status', models.TextField(default='Not connected')),
            ],
        ),
    ]
