# Copyright (c) 2022-2023 IO-Aero. All rights reserved. Use of this
# source code is governed by the IO-Aero License, that can
# be found in the LICENSE.md file.

"""Module stub file."""
import argparse

ARG_CORRECTION: str
ARG_MSACCESS: str
ARG_MSEXCEL: str
ARG_TASK: str

def check_arg_msaccess(args: argparse.Namespace) -> None: ...
def check_arg_msexcel(args: argparse.Namespace) -> None: ...
def check_arg_task(args: argparse.Namespace) -> None: ...
def cleansing_postgres_data() -> None: ...
def correct_dec_lat_lng() -> None: ...
def create_db_schema() -> None: ...
def download_ntsb_msaccess_file(msaccess: str) -> None: ...
def find_nearest_airports() -> None: ...
def generate_sql() -> None: ...
def get_args() -> None: ...
def initialise_logger() -> None: ...
def load_airport_data() -> None: ...
def load_aviation_occurrence_categories() -> None: ...
def load_correction_data(filename: str) -> None: ...
def load_country_state_data() -> None: ...
def load_ntsb_msaccess_data(msaccess: str) -> None: ...
def load_ntsb_primary_keys(msaccess: str) -> None: ...
def load_sequence_of_events() -> None: ...
def load_simplemaps_data() -> None: ...
def load_zip_code_db_data() -> None: ...
def progress_msg(msg: str) -> None: ...
def progress_msg_time_elapsed(duration: int, event: str) -> None: ...
def refresh_db_schema() -> None: ...
def terminate_fatal(error_msg: str) -> None: ...
def update_db_schema() -> None: ...
def verify_ntsb_data() -> None: ...
def version() -> str: ...
