# Generated by Django 4.0.5 on 2022-06-16 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canned_views", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cannedviews",
            name="columns",
            field=models.TextField(
                help_text="comma separated list of column names",
                null=True,
                validators=[django.core.validators.RegexValidator(regex="^([0-9a-z_,])+$")],
            ),
        ),
        migrations.AddField(
            model_name="cannedviews",
            name="order_by",
            field=models.TextField(
                null=True,
                validators=[django.core.validators.RegexValidator(regex="^([0-9a-z ])+$")],
            ),
        ),
        migrations.AddField(
            model_name="cannedviews",
            name="where",
            field=models.TextField(
                null=True,
                validators=[django.core.validators.RegexValidator(regex="^([0-9a-z ])+$")],
            ),
        ),
        migrations.AddField(
            model_name="historicalcannedviews",
            name="columns",
            field=models.TextField(
                help_text="comma separated list of column names",
                null=True,
                validators=[django.core.validators.RegexValidator(regex="^([0-9a-z_,])+$")],
            ),
        ),
        migrations.AddField(
            model_name="historicalcannedviews",
            name="order_by",
            field=models.TextField(
                null=True,
                validators=[django.core.validators.RegexValidator(regex="^([0-9a-z ])+$")],
            ),
        ),
        migrations.AddField(
            model_name="historicalcannedviews",
            name="where",
            field=models.TextField(
                null=True,
                validators=[django.core.validators.RegexValidator(regex="^([0-9a-z ])+$")],
            ),
        ),
    ]
