# Generated by Django 4.0.5 on 2022-06-16 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("canned_views", "0002_cannedviews_columns_cannedviews_order_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cannedviews",
            name="columns",
        ),
        migrations.RemoveField(
            model_name="cannedviews",
            name="order_by",
        ),
        migrations.RemoveField(
            model_name="cannedviews",
            name="where",
        ),
        migrations.RemoveField(
            model_name="historicalcannedviews",
            name="columns",
        ),
        migrations.RemoveField(
            model_name="historicalcannedviews",
            name="order_by",
        ),
        migrations.RemoveField(
            model_name="historicalcannedviews",
            name="where",
        ),
    ]
