# Generated by Django 3.2.13 on 2022-09-29 14:42

from django.db import migrations
import django.db.models.manager
import edc_sites.models


class Migration(migrations.Migration):
    dependencies = [
        ("canned_views", "0009_auto_20220704_1841"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="cannedview",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("sites", edc_sites.models.CurrentSiteManager()),
                ("on_site", edc_sites.models.CurrentSiteManager()),
            ],
        ),
    ]
