from avijit1996iiti_basic_calculator.addition import Addition
from avijit1996iiti_basic_calculator.substraction import Substraction
from avijit1996iiti_basic_calculator.multiplication import Multiplication
from avijit1996iiti_basic_calculator.division import Division
