# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '0.1.dev127+gc5b6498.d20230629'
version_tuple = (0, 1, 'dev127', 'gc5b6498.d20230629')
