
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-08T10:55:50-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "6e947774e2ceee90a52c79e4e2634bf1e2bdf92d",
 "version": "0.1.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
