INVOICE_BILLER_FORM_TYPE = 'I'
REGULAR_BILLER_FORM_TYPE = 'R'

BILLER_FORM_TYPES = (
    (INVOICE_BILLER_FORM_TYPE, "Invoice"),
    (REGULAR_BILLER_FORM_TYPE, "Regular"),
)

INITIALIZED_TRANSACTION_STATUS = "I"
FAILED_TRANSACTION_STATUS = "F"
SUCCESSFUL_TRANSACTION_STATUS = "S"
PENDING_TRANSACTION_STATUS = "P"
TRANSACTION_STATUSES = (
    (INITIALIZED_TRANSACTION_STATUS, "Initialized"),
    (FAILED_TRANSACTION_STATUS, "Failed"),
    (SUCCESSFUL_TRANSACTION_STATUS, "Successful"),
    (PENDING_TRANSACTION_STATUS, "Pending"),
)
