# Generated by Django 2.2.28 on 2023-07-20 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_babelfish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babelfishprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='babelfish_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
