# Generated by Django 4.1.7 on 2023-03-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_deletedviacascade_accountconfig_deleted_via_cascade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biller',
            name='requires_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='requires_consent',
            field=models.BooleanField(default=False),
        ),
    ]
