# Generated by Django 4.2 on 2023-05-14 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_billerform_billerformfield_billerformproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_via_cascade', models.BooleanField(default=False, editable=False)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_by_id', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('txn_id', models.CharField(max_length=255)),
                ('customer_acct_no', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('provider_acct_no', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('F', 'Failed'), ('S', 'Successful'), ('P', 'Pending')], default='P', max_length=1)),
                ('status_reason', models.TextField(default='Transaction is pending')),
                ('channel_txn_id', models.CharField(max_length=255)),
                ('customer_id', models.CharField(blank=True, max_length=30, null=True)),
                ('is_debited', models.BooleanField(default=False)),
                ('debit_response_code', models.CharField(blank=True, max_length=30, null=True)),
                ('debited_on', models.DateTimeField(blank=True, null=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('reversal_response_code', models.CharField(blank=True, max_length=30, null=True)),
                ('reversed_on', models.DateTimeField(blank=True, null=True)),
                ('requery_count', models.IntegerField(default=0)),
                ('provider_resp_status', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_resp_desc', models.TextField(blank=True, null=True)),
                ('biller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.biller')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.channel')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.provider')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
