# This file automatically generated by
#    C:\Jenkins\workspace\python\sdk\python-packaging-pipeline\py-client\.\couchbase_version.py
# at
#    2023-08-08 09:15:03.855599
__version__ = '4.1.7rc1'