
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-04T16:24:09-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "f1141993a11197c142ce0264d64111a0055f85ee",
 "version": "2.18.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
