
# This file was generated by 'versioneer.py' (0.27) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-03T11:16:36-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "53e8777c0222028ef3f5069621c65437d5c7965c",
 "version": "2023.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
