VERSION_YEAR = 2023
VERSION_MONTH = int('08')
VERSION_DAY = int('03')
VERSION_HOUR = int('16')
VERSION_MINUTE = int('54')
MAJOR_VERSION = 1
MINOR_VERSION = 5
PATCH_VERSION = 202308031654
version_date = '2023/08/03 16:54'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
