# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qwak/workspace/workspace.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from _qwak_proto.qwak.user_application.common.v0 import resources_pb2 as qwak_dot_user__application_dot_common_dot_v0_dot_resources__pb2
from _qwak_proto.qwak.user_application.v0 import user_application_pb2 as qwak_dot_user__application_dot_v0_dot_user__application__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eqwak/workspace/workspace.proto\x12\x19qwak.workspace.management\x1a\x1fgoogle/protobuf/timestamp.proto\x1a/qwak/user_application/common/v0/resources.proto\x1a/qwak/user_application/v0/user_application.proto\"\xe6\x02\n\tWorkspace\x12\x16\n\x0eworkspace_name\x18\x01 \x01(\t\x12`\n\x1c\x63lient_pod_compute_resources\x18\x02 \x01(\x0b\x32:.qwak.user_application.common.v0.ClientPodComputeResources\x12\x12\n\nimage_type\x18\x03 \x01(\t\x12\x17\n\x0f\x63reator_user_id\x18\x04 \x01(\t\x12\x1b\n\x13last_update_user_id\x18\x05 \x01(\t\x12/\n\x0b\x63reate_time\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x34\n\x10last_update_time\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x18\n\x10workspace_status\x18\n \x01(\t\x12\x14\n\x0cworkspace_id\x18\x0b \x01(\t\"\xa5\x01\n\x15WorkspaceCreationSpec\x12\x16\n\x0eworkspace_name\x18\x01 \x01(\t\x12`\n\x1c\x63lient_pod_compute_resources\x18\x02 \x01(\x0b\x32:.qwak.user_application.common.v0.ClientPodComputeResources\x12\x12\n\nimage_type\x18\x03 \x01(\t\"\xdf\x01\n\x1bWorkspaceDeploymentSnapshot\x12\x16\n\x0eworkspace_name\x18\x01 \x01(\t\x12\x14\n\x0cworkspace_id\x18\x02 \x01(\t\x12\x32\n\ndeployment\x18\x03 \x01(\x0b\x32\x1e.qwak.user_application.v0.Spec\x12\x30\n\x08replicas\x18\x04 \x03(\x0b\x32\x1e.qwak.user_application.v0.Spec\x12,\n\x04pods\x18\x05 \x03(\x0b\x32\x1e.qwak.user_application.v0.Spec\"\xb1\x01\n$UpdateWorkspaceStatusFromEdgeDetails\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x16\n\x0e\x65nvironment_id\x18\x02 \x01(\t\x12]\n\x1dworkspace_deployment_snapshot\x18\x03 \x03(\x0b\x32\x36.qwak.workspace.management.WorkspaceDeploymentSnapshot\"*\n\x0eWorkspaceImage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\tBB\n$com.qwak.ai.management.workspace.apiP\x01Z\x18qwak/workspace;workspaceb\x06proto3')



_WORKSPACE = DESCRIPTOR.message_types_by_name['Workspace']
_WORKSPACECREATIONSPEC = DESCRIPTOR.message_types_by_name['WorkspaceCreationSpec']
_WORKSPACEDEPLOYMENTSNAPSHOT = DESCRIPTOR.message_types_by_name['WorkspaceDeploymentSnapshot']
_UPDATEWORKSPACESTATUSFROMEDGEDETAILS = DESCRIPTOR.message_types_by_name['UpdateWorkspaceStatusFromEdgeDetails']
_WORKSPACEIMAGE = DESCRIPTOR.message_types_by_name['WorkspaceImage']
Workspace = _reflection.GeneratedProtocolMessageType('Workspace', (_message.Message,), {
  'DESCRIPTOR' : _WORKSPACE,
  '__module__' : 'qwak.workspace.workspace_pb2'
  # @@protoc_insertion_point(class_scope:qwak.workspace.management.Workspace)
  })
_sym_db.RegisterMessage(Workspace)

WorkspaceCreationSpec = _reflection.GeneratedProtocolMessageType('WorkspaceCreationSpec', (_message.Message,), {
  'DESCRIPTOR' : _WORKSPACECREATIONSPEC,
  '__module__' : 'qwak.workspace.workspace_pb2'
  # @@protoc_insertion_point(class_scope:qwak.workspace.management.WorkspaceCreationSpec)
  })
_sym_db.RegisterMessage(WorkspaceCreationSpec)

WorkspaceDeploymentSnapshot = _reflection.GeneratedProtocolMessageType('WorkspaceDeploymentSnapshot', (_message.Message,), {
  'DESCRIPTOR' : _WORKSPACEDEPLOYMENTSNAPSHOT,
  '__module__' : 'qwak.workspace.workspace_pb2'
  # @@protoc_insertion_point(class_scope:qwak.workspace.management.WorkspaceDeploymentSnapshot)
  })
_sym_db.RegisterMessage(WorkspaceDeploymentSnapshot)

UpdateWorkspaceStatusFromEdgeDetails = _reflection.GeneratedProtocolMessageType('UpdateWorkspaceStatusFromEdgeDetails', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEWORKSPACESTATUSFROMEDGEDETAILS,
  '__module__' : 'qwak.workspace.workspace_pb2'
  # @@protoc_insertion_point(class_scope:qwak.workspace.management.UpdateWorkspaceStatusFromEdgeDetails)
  })
_sym_db.RegisterMessage(UpdateWorkspaceStatusFromEdgeDetails)

WorkspaceImage = _reflection.GeneratedProtocolMessageType('WorkspaceImage', (_message.Message,), {
  'DESCRIPTOR' : _WORKSPACEIMAGE,
  '__module__' : 'qwak.workspace.workspace_pb2'
  # @@protoc_insertion_point(class_scope:qwak.workspace.management.WorkspaceImage)
  })
_sym_db.RegisterMessage(WorkspaceImage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n$com.qwak.ai.management.workspace.apiP\001Z\030qwak/workspace;workspace'
  _WORKSPACE._serialized_start=193
  _WORKSPACE._serialized_end=551
  _WORKSPACECREATIONSPEC._serialized_start=554
  _WORKSPACECREATIONSPEC._serialized_end=719
  _WORKSPACEDEPLOYMENTSNAPSHOT._serialized_start=722
  _WORKSPACEDEPLOYMENTSNAPSHOT._serialized_end=945
  _UPDATEWORKSPACESTATUSFROMEDGEDETAILS._serialized_start=948
  _UPDATEWORKSPACESTATUSFROMEDGEDETAILS._serialized_end=1125
  _WORKSPACEIMAGE._serialized_start=1127
  _WORKSPACEIMAGE._serialized_end=1169
# @@protoc_insertion_point(module_scope)
