
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-02T14:28:28+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "397a3e004d122d2d8a65ef5a6beb40176e9058b9",
 "version": "2.2.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
