# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pysandwich/proto/io.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19pysandwich/proto/io.proto\x12\x15saq.sandwich.proto.io*\x9e\x01\n\x07IOError\x12\x0e\n\nIOERROR_OK\x10\x00\x12\x17\n\x13IOERROR_IN_PROGRESS\x10\x01\x12\x17\n\x13IOERROR_WOULD_BLOCK\x10\x02\x12\x13\n\x0fIOERROR_REFUSED\x10\x03\x12\x12\n\x0eIOERROR_CLOSED\x10\x04\x12\x13\n\x0fIOERROR_INVALID\x10\x05\x12\x13\n\x0fIOERROR_UNKNOWN\x10\x06\x42\x37Z5github.com/sandbox-quantum/sandwich/go/proto/sandwichb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pysandwich.proto.io_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z5github.com/sandbox-quantum/sandwich/go/proto/sandwich'
  _globals['_IOERROR']._serialized_start=53
  _globals['_IOERROR']._serialized_end=211
# @@protoc_insertion_point(module_scope)
