# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pysandwich/proto/tunnel.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dpysandwich/proto/tunnel.proto\x12\x19saq.sandwich.proto.tunnel*\xc0\x01\n\x05State\x12\x17\n\x13STATE_NOT_CONNECTED\x10\x00\x12 \n\x1cSTATE_CONNECTION_IN_PROGRESS\x10\x01\x12\x1f\n\x1bSTATE_HANDSHAKE_IN_PROGRESS\x10\x02\x12\x18\n\x14STATE_HANDSHAKE_DONE\x10\x03\x12\x18\n\x14STATE_BEING_SHUTDOWN\x10\x04\x12\x16\n\x12STATE_DISCONNECTED\x10\x05\x12\x0f\n\x0bSTATE_ERROR\x10\x06*\xa0\x01\n\x0eHandshakeState\x12\x1e\n\x1aHANDSHAKESTATE_IN_PROGRESS\x10\x00\x12\x17\n\x13HANDSHAKESTATE_DONE\x10\x01\x12\x1c\n\x18HANDSHAKESTATE_WANT_READ\x10\x02\x12\x1d\n\x19HANDSHAKESTATE_WANT_WRITE\x10\x03\x12\x18\n\x14HANDSHAKESTATE_ERROR\x10\x04*\xc2\x01\n\x0bRecordError\x12\x12\n\x0eRECORDERROR_OK\x10\x00\x12\x19\n\x15RECORDERROR_WANT_READ\x10\x01\x12\x1a\n\x16RECORDERROR_WANT_WRITE\x10\x02\x12\x1e\n\x1aRECORDERROR_BEING_SHUTDOWN\x10\x03\x12\x16\n\x12RECORDERROR_CLOSED\x10\x04\x12\x17\n\x13RECORDERROR_TOO_BIG\x10\x05\x12\x17\n\x13RECORDERROR_UNKNOWN\x10\x06\x42\x37Z5github.com/sandbox-quantum/sandwich/go/proto/sandwichb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pysandwich.proto.tunnel_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z5github.com/sandbox-quantum/sandwich/go/proto/sandwich'
  _globals['_STATE']._serialized_start=61
  _globals['_STATE']._serialized_end=253
  _globals['_HANDSHAKESTATE']._serialized_start=256
  _globals['_HANDSHAKESTATE']._serialized_end=416
  _globals['_RECORDERROR']._serialized_start=419
  _globals['_RECORDERROR']._serialized_end=613
# @@protoc_insertion_point(module_scope)
