
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-08T11:20:19-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6d6e5d9dbe1c3890a5a64c02ce7c12c53c8766b5",
 "version": "0.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
