
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-06T15:03:48+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": null,
 "version": "1.0.31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
