
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-06T21:48:51-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3c307a51910f2bd480ee364f2333dd3a767dfaf0",
 "version": "0.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
