# from .ui_Settings import Ui_Settings
# from .ui_AddUserDialog import Ui_AddUserDialog
# from .ui_RemoveUserDialog import Ui_RemoveUserDialog
# from .ui_LoginDialog import Ui_LoginDialog
# from .ui_HelpDialog import Ui_HelpDialog
# from .ui_MainWindow import Ui_MainWindow
# from .ui_ManualControlDialog import Ui_ManualControlDialog
# from .ui_HelpDialog import Ui_HelpDialog
# from .ui_LogView import Ui_LogView
# from .ui_About import Ui_About
# from . import ui_ManualControlDialog