"""
    Invision Community API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import invision_client
from invision_client.model.forums_topics_post_request_poll_options_inner_answers_inner import ForumsTopicsPostRequestPollOptionsInnerAnswersInner


class TestForumsTopicsPostRequestPollOptionsInnerAnswersInner(unittest.TestCase):
    """ForumsTopicsPostRequestPollOptionsInnerAnswersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testForumsTopicsPostRequestPollOptionsInnerAnswersInner(self):
        """Test ForumsTopicsPostRequestPollOptionsInnerAnswersInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ForumsTopicsPostRequestPollOptionsInnerAnswersInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
