"""
    Invision Community API Schema

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import invision_client
from invision_client.model.member import Member
from invision_client.model.post_reactions_inner import PostReactionsInner
globals()['Member'] = Member
globals()['PostReactionsInner'] = PostReactionsInner
from invision_client.model.post import Post


class TestPost(unittest.TestCase):
    """Post unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPost(self):
        """Test Post"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Post()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
