"""
    Invision Community API Schema

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import invision_client
from invision_client.api.forums_api import ForumsApi  # noqa: E501


class TestForumsApi(unittest.TestCase):
    """ForumsApi unit test stubs"""

    def setUp(self):
        self.api = ForumsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_forums_forums_get(self):
        """Test case for forums_forums_get

        Get list of forums  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
