"""
    Invision Community API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import invision_client
from invision_client.model.forum import Forum
from invision_client.model.post import Post
globals()['Forum'] = Forum
globals()['Post'] = Post
from invision_client.model.forums_topics_post200_response import ForumsTopicsPost200Response


class TestForumsTopicsPost200Response(unittest.TestCase):
    """ForumsTopicsPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testForumsTopicsPost200Response(self):
        """Test ForumsTopicsPost200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ForumsTopicsPost200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
