"""
    Invision Community API Schema

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import invision_client
from invision_client.model.question import Question


class TestQuestion(unittest.TestCase):
    """Question unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQuestion(self):
        """Test Question"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Question()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
