"""
    Invision Community API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import invision_client
from invision_client.model.field import Field
globals()['Field'] = Field
from invision_client.model.field_group import FieldGroup


class TestFieldGroup(unittest.TestCase):
    """FieldGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFieldGroup(self):
        """Test FieldGroup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FieldGroup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
