"""
    Invision Community API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import invision_client
from invision_client.model.poll_option_object_answers_inner import PollOptionObjectAnswersInner
globals()['PollOptionObjectAnswersInner'] = PollOptionObjectAnswersInner
from invision_client.model.poll_option_object import PollOptionObject


class TestPollOptionObject(unittest.TestCase):
    """PollOptionObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPollOptionObject(self):
        """Test PollOptionObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PollOptionObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
