# Generated by Django 4.2 on 2023-07-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_silly_stripe', '0006_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
