
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-03T16:41:03-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "fe13e3fe94b2388a8a2e78455f2001b853fa9a99",
 "version": "0.0.1111.post.dev17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
