
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-04T09:47:33+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d2431e8a872021c358c90cec61e1b94af5e68b93",
 "version": "2.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
