
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-07T14:30:59+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "6e44c8271572073eea25da2401c7352d6687ed8b",
 "version": "1.5.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
