# Generated by Django 3.2.13 on 2022-06-17 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canned_views", "0003_remove_cannedviews_columns_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cannedviews",
            name="sql_select_columns",
            field=models.TextField(
                blank=True,
                help_text="Comma separated list of field names for the SQL SELECT. All lowercase, no spaces",
                null=True,
                validators=[django.core.validators.RegexValidator(regex="^([a-z0-9_,])+$")],
            ),
        ),
        migrations.AddField(
            model_name="historicalcannedviews",
            name="sql_select_columns",
            field=models.TextField(
                blank=True,
                help_text="Comma separated list of field names for the SQL SELECT. All lowercase, no spaces",
                null=True,
                validators=[django.core.validators.RegexValidator(regex="^([a-z0-9_,])+$")],
            ),
        ),
        migrations.AlterField(
            model_name="cannedviews",
            name="sql_view_name",
            field=models.CharField(
                max_length=50,
                null=True,
                validators=[django.core.validators.RegexValidator(regex="^([a-z0-9_])+$")],
            ),
        ),
        migrations.AlterField(
            model_name="historicalcannedviews",
            name="sql_view_name",
            field=models.CharField(
                max_length=50,
                null=True,
                validators=[django.core.validators.RegexValidator(regex="^([a-z0-9_])+$")],
            ),
        ),
    ]
