# Generated by Django 4.0.5 on 2022-06-26 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canned_views", "0006_cannedviews_filter_by_current_site_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cannedviews",
            name="linked_column_name",
            field=models.CharField(default="subject_identifier", max_length=50),
        ),
        migrations.AddField(
            model_name="cannedviews",
            name="reverse_url",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], default="No", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="cannedviews",
            name="reverse_url_args",
            field=models.CharField(
                help_text="column names separated by comma. For example, subject_identifier,visit_code,visit_code_sequence,visit_schedule_name,schedule_name.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cannedviews",
            name="reverse_url_name",
            field=models.CharField(
                help_text="a valid url name as a `key` for the `value` stored in the `url_names` dictionary. For example, `subject_dashboard_url`.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcannedviews",
            name="linked_column_name",
            field=models.CharField(default="subject_identifier", max_length=50),
        ),
        migrations.AddField(
            model_name="historicalcannedviews",
            name="reverse_url",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], default="No", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="historicalcannedviews",
            name="reverse_url_args",
            field=models.CharField(
                help_text="column names separated by comma. For example, subject_identifier,visit_code,visit_code_sequence,visit_schedule_name,schedule_name.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcannedviews",
            name="reverse_url_name",
            field=models.CharField(
                help_text="a valid url name as a `key` for the `value` stored in the `url_names` dictionary. For example, `subject_dashboard_url`.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cannedviews",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Appears in the report header. A clear descrtiption of the report and its intended use.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cannedviews",
            name="display_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="cannedviews",
            name="filter_by_current_site",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                help_text="If yes, the column `site_id` is expected",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cannedviews",
            name="instructions",
            field=models.TextField(
                blank=True,
                help_text="Appears in the report header. Instructions for the user of the report",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cannedviews",
            name="name",
            field=models.CharField(
                max_length=30,
                validators=[django.core.validators.RegexValidator(regex="^([a-z0-9_])+$")],
            ),
        ),
        migrations.AlterField(
            model_name="historicalcannedviews",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Appears in the report header. A clear descrtiption of the report and its intended use.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcannedviews",
            name="display_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="historicalcannedviews",
            name="filter_by_current_site",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                help_text="If yes, the column `site_id` is expected",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcannedviews",
            name="instructions",
            field=models.TextField(
                blank=True,
                help_text="Appears in the report header. Instructions for the user of the report",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcannedviews",
            name="name",
            field=models.CharField(
                max_length=30,
                validators=[django.core.validators.RegexValidator(regex="^([a-z0-9_])+$")],
            ),
        ),
    ]
