# Generated by Django 4.2.1 on 2023-07-05 02:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("canned_views", "0010_alter_cannedview_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cannedview",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "get_latest_by": "modified",
                "ordering": ("-modified", "-created"),
                "verbose_name": "Canned View",
                "verbose_name_plural": "Canned Views",
            },
        ),
    ]
