
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-08T14:37:34-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "21ac7b9c17c873fc7cdbbebf39cff810b49aa8e6",
 "version": "2.5.0.4rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
