
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-04T05:12:29-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "a42425b66d3266e7d2d42e494a0610c534e093ff",
 "version": "0.29.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
