
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-20T18:48:57-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f0fe1d30bc67c033ecf247bb93ed1cf4f2b744c5",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
