# coding: utf-8

"""
    Cashfree LRS

    CashFree LRS APIs (v2)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: nextgenapi@cashfree.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import cashfree_lrs_client
from cashfree_lrs_client.models.create_order_request import CreateOrderRequest  # noqa: E501
from cashfree_lrs_client.rest import ApiException

class TestCreateOrderRequest(unittest.TestCase):
    """CreateOrderRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateOrderRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOrderRequest`
        """
        model = cashfree_lrs_client.models.create_order_request.CreateOrderRequest()  # noqa: E501
        if include_optional :
            return CreateOrderRequest(
                order_id = '0', 
                to_currency = 'USD', 
                to_amount = 1, 
                from_amount = 1, 
                purpose = 'EDUCATION', 
                return_url = '012', 
                remitter_id = '0', 
                beneficiary_id = '0', 
                customer_declaration = '', 
                doc_ids = '', 
                customer_relationship = 'SELF', 
                education_loan = True, 
                remarks = ''
            )
        else :
            return CreateOrderRequest(
                order_id = '0',
                to_currency = 'USD',
                to_amount = 1,
                purpose = 'EDUCATION',
                return_url = '012',
                remitter_id = '0',
                beneficiary_id = '0',
                customer_relationship = 'SELF',
        )
        """

    def testCreateOrderRequest(self):
        """Test CreateOrderRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
