# coding: utf-8

"""
    Cashfree LRS

    CashFree LRS APIs (v2)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: nextgenapi@cashfree.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import cashfree_lrs_client
from cashfree_lrs_client.models.fetch_forex_rate_request import FetchForexRateRequest  # noqa: E501
from cashfree_lrs_client.rest import ApiException

class TestFetchForexRateRequest(unittest.TestCase):
    """FetchForexRateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test FetchForexRateRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FetchForexRateRequest`
        """
        model = cashfree_lrs_client.models.fetch_forex_rate_request.FetchForexRateRequest()  # noqa: E501
        if include_optional :
            return FetchForexRateRequest(
                to_currency = 'USD', 
                to_amount = 1.337, 
                purpose = 'EDUCATION', 
                remitter_id = '012', 
                customer_declaration = 1.337
            )
        else :
            return FetchForexRateRequest(
                to_currency = 'USD',
                to_amount = 1.337,
                purpose = 'EDUCATION',
        )
        """

    def testFetchForexRateRequest(self):
        """Test FetchForexRateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
