# coding: utf-8

"""
    Cashfree LRS

    CashFree LRS APIs (v2)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: nextgenapi@cashfree.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import cashfree_lrs_client
from cashfree_lrs_client.models.purpose import Purpose  # noqa: E501
from cashfree_lrs_client.rest import ApiException

class TestPurpose(unittest.TestCase):
    """Purpose unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPurpose(self):
        """Test Purpose"""
        # inst = Purpose()

if __name__ == '__main__':
    unittest.main()
