# coding: utf-8

"""
    Cashfree LRS

    CashFree LRS APIs (v2)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: nextgenapi@cashfree.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import cashfree_lrs_client
from cashfree_lrs_client.models.setup_webhooks_request import SetupWebhooksRequest  # noqa: E501
from cashfree_lrs_client.rest import ApiException

class TestSetupWebhooksRequest(unittest.TestCase):
    """SetupWebhooksRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SetupWebhooksRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetupWebhooksRequest`
        """
        model = cashfree_lrs_client.models.setup_webhooks_request.SetupWebhooksRequest()  # noqa: E501
        if include_optional :
            return SetupWebhooksRequest(
                payment_url = '', 
                refund_url = '', 
                order_url = ''
            )
        else :
            return SetupWebhooksRequest(
                payment_url = '',
                refund_url = '',
                order_url = '',
        )
        """

    def testSetupWebhooksRequest(self):
        """Test SetupWebhooksRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
