# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGroupBox, QHBoxLayout,
    QLabel, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QTextEdit, QVBoxLayout,
    QWidget)
import resource_rc
import icons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(900, 788)
        MainWindow.setMinimumSize(QSize(900, 700))
        font = QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        MainWindow.setAcceptDrops(True)
        icon = QIcon()
        icon.addFile(u":/resources/icons/images/icons/geometric.png", QSize(), QIcon.Normal, QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QSize(32, 32))
        MainWindow.setToolButtonStyle(Qt.ToolButtonTextBesideIcon)
        self.actionConnect = QAction(MainWindow)
        self.actionConnect.setObjectName(u"actionConnect")
        icon1 = QIcon()
        icon1.addFile(u":/resources/icons/images/icons/usb3.png", QSize(), QIcon.Normal, QIcon.Off)
        icon1.addFile(u":/resources/icons/images/icons/usb.png", QSize(), QIcon.Normal, QIcon.On)
        icon1.addFile(u":/resources/icons/images/icons/usb.png", QSize(), QIcon.Selected, QIcon.On)
        self.actionConnect.setIcon(icon1)
        self.actionConnect.setFont(font)
        self.actionConnect.setShortcutContext(Qt.WidgetShortcut)
        self.actionLogout = QAction(MainWindow)
        self.actionLogout.setObjectName(u"actionLogout")
        icon2 = QIcon()
        icon2.addFile(u":/resources/icons/images/icons/remove-user.png", QSize(), QIcon.Normal, QIcon.Off)
        icon2.addFile(u":/resources/icons/images/icons/remove-user.png", QSize(), QIcon.Normal, QIcon.On)
        self.actionLogout.setIcon(icon2)
        self.actionLogout.setFont(font)
        self.actionExit_2 = QAction(MainWindow)
        self.actionExit_2.setObjectName(u"actionExit_2")
        icon3 = QIcon()
        icon3.addFile(u":/resources/icons/images/icons/logout2.png", QSize(), QIcon.Normal, QIcon.Off)
        icon3.addFile(u":/resources/icons/images/icons/logout2.png", QSize(), QIcon.Disabled, QIcon.Off)
        self.actionExit_2.setIcon(icon3)
        self.actionExit_2.setFont(font)
        self.actionExit_2.setMenuRole(QAction.QuitRole)
        self.actionEAX300 = QAction(MainWindow)
        self.actionEAX300.setObjectName(u"actionEAX300")
        self.actionEAX300.setCheckable(True)
        icon4 = QIcon()
        icon4.addFile(u":/resources/icons/images/icons/radio-off-button.png", QSize(), QIcon.Selected, QIcon.Off)
        icon4.addFile(u":/resources/icons/images/icons/radio-on-button.png", QSize(), QIcon.Selected, QIcon.On)
        self.actionEAX300.setIcon(icon4)
        font1 = QFont()
        font1.setPointSize(11)
        font1.setBold(False)
        self.actionEAX300.setFont(font1)
        self.actionEAX500 = QAction(MainWindow)
        self.actionEAX500.setObjectName(u"actionEAX500")
        self.actionEAX500.setCheckable(True)
        self.actionEAX500.setIcon(icon4)
        self.actionEAX500.setFont(font)
        self.actionEAX500.setMenuRole(QAction.TextHeuristicRole)
        self.actionEAX503 = QAction(MainWindow)
        self.actionEAX503.setObjectName(u"actionEAX503")
        self.actionEAX503.setCheckable(True)
        self.actionEAX503.setIcon(icon4)
        self.actionEAX503.setFont(font)
        self.actionEAX503.setMenuRole(QAction.TextHeuristicRole)
        self.actionEAX504 = QAction(MainWindow)
        self.actionEAX504.setObjectName(u"actionEAX504")
        self.actionEAX504.setCheckable(True)
        self.actionEAX504.setIcon(icon4)
        self.actionEAX504.setFont(font)
        self.actionEAX504.setMenuRole(QAction.TextHeuristicRole)
        self.actionEAX505 = QAction(MainWindow)
        self.actionEAX505.setObjectName(u"actionEAX505")
        self.actionEAX505.setCheckable(True)
        self.actionEAX505.setIcon(icon4)
        self.actionEAX505.setFont(font)
        self.actionEAX505.setMenuRole(QAction.TextHeuristicRole)
        self.actionEAX510 = QAction(MainWindow)
        self.actionEAX510.setObjectName(u"actionEAX510")
        self.actionEAX510.setCheckable(True)
        self.actionEAX510.setIcon(icon4)
        self.actionEAX510.setFont(font)
        self.actionEAX510.setMenuRole(QAction.TextHeuristicRole)
        self.actionEAX513 = QAction(MainWindow)
        self.actionEAX513.setObjectName(u"actionEAX513")
        self.actionEAX513.setCheckable(True)
        self.actionEAX513.setIcon(icon4)
        self.actionEAX513.setFont(font)
        self.actionEAX513.setMenuRole(QAction.TextHeuristicRole)
        self.actionEAX514 = QAction(MainWindow)
        self.actionEAX514.setObjectName(u"actionEAX514")
        self.actionEAX514.setCheckable(True)
        self.actionEAX514.setIcon(icon4)
        self.actionEAX514.setFont(font)
        self.actionEAX514.setMenuRole(QAction.TextHeuristicRole)
        self.actionEAX515 = QAction(MainWindow)
        self.actionEAX515.setObjectName(u"actionEAX515")
        self.actionEAX515.setCheckable(True)
        self.actionEAX515.setIcon(icon4)
        self.actionEAX515.setFont(font)
        self.actionEAX515.setMenuRole(QAction.TextHeuristicRole)
        self.actionEAX520 = QAction(MainWindow)
        self.actionEAX520.setObjectName(u"actionEAX520")
        self.actionEAX520.setCheckable(True)
        self.actionEAX520.setIcon(icon4)
        self.actionEAX520.setFont(font)
        self.actionEAX520.setMenuRole(QAction.TextHeuristicRole)
        self.actionEAX523 = QAction(MainWindow)
        self.actionEAX523.setObjectName(u"actionEAX523")
        self.actionEAX523.setCheckable(True)
        self.actionEAX523.setIcon(icon4)
        self.actionEAX523.setFont(font)
        self.actionEAX523.setMenuRole(QAction.TextHeuristicRole)
        self.actionEAX524 = QAction(MainWindow)
        self.actionEAX524.setObjectName(u"actionEAX524")
        self.actionEAX524.setCheckable(True)
        self.actionEAX524.setIcon(icon4)
        self.actionEAX524.setFont(font)
        self.actionEAX524.setMenuRole(QAction.TextHeuristicRole)
        self.actionEAX525 = QAction(MainWindow)
        self.actionEAX525.setObjectName(u"actionEAX525")
        self.actionEAX525.setCheckable(True)
        self.actionEAX525.setIcon(icon4)
        self.actionEAX525.setFont(font)
        self.actionEAX525.setMenuRole(QAction.TextHeuristicRole)
        self.actionChange_font = QAction(MainWindow)
        self.actionChange_font.setObjectName(u"actionChange_font")
        icon5 = QIcon()
        icon5.addFile(u":/resources/icons/images/icons/size.png", QSize(), QIcon.Normal, QIcon.On)
        self.actionChange_font.setIcon(icon5)
        self.actionChange_font.setFont(font)
        self.actionModify_Settings = QAction(MainWindow)
        self.actionModify_Settings.setObjectName(u"actionModify_Settings")
        icon6 = QIcon()
        icon6.addFile(u":/resources/icons/images/icons/settings.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.actionModify_Settings.setIcon(icon6)
        self.actionModify_Settings.setFont(font)
        self.actionAdd_User = QAction(MainWindow)
        self.actionAdd_User.setObjectName(u"actionAdd_User")
        icon7 = QIcon()
        icon7.addFile(u":/resources/icons/images/icons/follow.png", QSize(), QIcon.Normal, QIcon.Off)
        icon7.addFile(u":/resources/icons/images/icons/follow.png", QSize(), QIcon.Normal, QIcon.On)
        self.actionAdd_User.setIcon(icon7)
        self.actionAdd_User.setFont(font)
        self.actionRemove_User = QAction(MainWindow)
        self.actionRemove_User.setObjectName(u"actionRemove_User")
        icon8 = QIcon()
        icon8.addFile(u":/resources/icons/images/icons/remove-user.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionRemove_User.setIcon(icon8)
        self.actionRemove_User.setFont(font)
        self.actionShow_Logs = QAction(MainWindow)
        self.actionShow_Logs.setObjectName(u"actionShow_Logs")
        icon9 = QIcon()
        icon9.addFile(u":/resources/icons/images/icons/files.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionShow_Logs.setIcon(icon9)
        self.actionShow_Logs.setFont(font)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        icon10 = QIcon()
        icon10.addFile(u":/resources/icons/images/icons/information.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAbout.setIcon(icon10)
        self.actionAbout.setFont(font)
        self.actionAbout.setShortcutContext(Qt.ApplicationShortcut)
        self.actionAbout.setMenuRole(QAction.AboutQtRole)
        self.actionManual_Control = QAction(MainWindow)
        self.actionManual_Control.setObjectName(u"actionManual_Control")
        icon11 = QIcon()
        icon11.addFile(u":/resources/icons/images/icons/gear.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionManual_Control.setIcon(icon11)
        self.actionManual_Control.setFont(font)
        self.actionChip_Select = QAction(MainWindow)
        self.actionChip_Select.setObjectName(u"actionChip_Select")
        icon12 = QIcon()
        icon12.addFile(u":/resources/icons/images/icons/chip.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionChip_Select.setIcon(icon12)
        self.actionChip_Select.setFont(font)
        self.actionUpdate_Firmware = QAction(MainWindow)
        self.actionUpdate_Firmware.setObjectName(u"actionUpdate_Firmware")
        icon13 = QIcon()
        icon13.addFile(u":/resources/icons/images/icons/ps.png", QSize(), QIcon.Normal, QIcon.On)
        self.actionUpdate_Firmware.setIcon(icon13)
        self.actionUpdate_Firmware.setFont(font)
        self.actionExplore_Directory = QAction(MainWindow)
        self.actionExplore_Directory.setObjectName(u"actionExplore_Directory")
        icon14 = QIcon()
        icon14.addFile(u":/resources/icons/images/icons/icons8-folder.png", QSize(), QIcon.Normal, QIcon.On)
        self.actionExplore_Directory.setIcon(icon14)
        self.actionExplore_Directory.setFont(font)
        self.actionHelp = QAction(MainWindow)
        self.actionHelp.setObjectName(u"actionHelp")
        icon15 = QIcon()
        icon15.addFile(u":/resources/icons/images/icons/help.png", QSize(), QIcon.Normal, QIcon.On)
        self.actionHelp.setIcon(icon15)
        self.actionHelp.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.text_edit = QTextEdit(self.centralwidget)
        self.text_edit.setObjectName(u"text_edit")
        font2 = QFont()
        font2.setFamilies([u"Calibri"])
        font2.setPointSize(16)
        self.text_edit.setFont(font2)
        self.text_edit.setMouseTracking(True)
        self.text_edit.setFocusPolicy(Qt.NoFocus)
        self.text_edit.setAutoFillBackground(False)
        self.text_edit.setStyleSheet(u"")
        self.text_edit.setFrameShape(QFrame.WinPanel)
        self.text_edit.setFrameShadow(QFrame.Sunken)
        self.text_edit.setAutoFormatting(QTextEdit.AutoAll)
        self.text_edit.setUndoRedoEnabled(False)
        self.text_edit.setReadOnly(True)
        self.text_edit.setTextInteractionFlags(Qt.NoTextInteraction)

        self.verticalLayout.addWidget(self.text_edit)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.program_button = QPushButton(self.centralwidget)
        self.program_button.setObjectName(u"program_button")
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.program_button.sizePolicy().hasHeightForWidth())
        self.program_button.setSizePolicy(sizePolicy)
        self.program_button.setMinimumSize(QSize(0, 80))
        self.program_button.setBaseSize(QSize(0, 0))
        font3 = QFont()
        font3.setPointSize(18)
        self.program_button.setFont(font3)
        icon16 = QIcon()
        icon16.addFile(u":/resources/icons/images/icons/prog-button.png", QSize(), QIcon.Normal, QIcon.Off)
        self.program_button.setIcon(icon16)
        self.program_button.setIconSize(QSize(100, 100))
        self.program_button.setFlat(True)

        self.horizontalLayout_3.addWidget(self.program_button)

        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setMinimumSize(QSize(0, 0))
        self.groupBox_2.setMaximumSize(QSize(16777215, 16777215))
        self.horizontalLayout_2 = QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.device_label = QLabel(self.groupBox_2)
        self.device_label.setObjectName(u"device_label")
        self.device_label.setMinimumSize(QSize(0, 0))
        font4 = QFont()
        font4.setPointSize(14)
        font4.setBold(True)
        self.device_label.setFont(font4)
        self.device_label.setStyleSheet(u"color: rgb(255, 0, 0);\n"
"/*image: url(:/resources/icons/images/detex_dark.png);*/\n"
"font-weight: bold;")
        self.device_label.setFrameShape(QFrame.NoFrame)
        self.device_label.setFrameShadow(QFrame.Sunken)
        self.device_label.setTextFormat(Qt.RichText)
        self.device_label.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_2.addWidget(self.device_label)


        self.horizontalLayout_3.addWidget(self.groupBox_2)

        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setMinimumSize(QSize(0, 0))
        self.horizontalLayout = QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.label_usb_icon = QLabel(self.groupBox)
        self.label_usb_icon.setObjectName(u"label_usb_icon")
        self.label_usb_icon.setMinimumSize(QSize(0, 0))
        self.label_usb_icon.setMaximumSize(QSize(48, 65))
        font5 = QFont()
        font5.setPointSize(9)
        font5.setBold(False)
        font5.setKerning(False)
        self.label_usb_icon.setFont(font5)
        self.label_usb_icon.setAutoFillBackground(False)
        self.label_usb_icon.setStyleSheet(u"")
        self.label_usb_icon.setFrameShape(QFrame.NoFrame)
        self.label_usb_icon.setFrameShadow(QFrame.Sunken)
        self.label_usb_icon.setTextFormat(Qt.AutoText)
        self.label_usb_icon.setScaledContents(False)
        self.label_usb_icon.setAlignment(Qt.AlignCenter)

        self.horizontalLayout.addWidget(self.label_usb_icon)

        self.usb_label = QLabel(self.groupBox)
        self.usb_label.setObjectName(u"usb_label")
        palette = QPalette()
        brush = QBrush(QColor(255, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush1 = QBrush(QColor(255, 0, 0, 128))
        brush1.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush1)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush1)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush1)
#endif
        self.usb_label.setPalette(palette)
        self.usb_label.setFont(font4)
        self.usb_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.usb_label.setMargin(9)

        self.horizontalLayout.addWidget(self.usb_label)


        self.horizontalLayout_3.addWidget(self.groupBox)

        self.test_button = QPushButton(self.centralwidget)
        self.test_button.setObjectName(u"test_button")
        self.test_button.setMinimumSize(QSize(158, 80))
        self.test_button.setMaximumSize(QSize(16777215, 80))
        font6 = QFont()
        font6.setPointSize(20)
        font6.setBold(False)
        self.test_button.setFont(font6)
        icon17 = QIcon()
        iconThemeName = u"document-print"
        if QIcon.hasThemeIcon(iconThemeName):
            icon17 = QIcon.fromTheme(iconThemeName)
        else:
            icon17.addFile(u":/resources/icons/images/icons/test-button.png", QSize(), QIcon.Normal, QIcon.On)

        self.test_button.setIcon(icon17)
        self.test_button.setIconSize(QSize(100, 100))
        self.test_button.setAutoDefault(False)
        self.test_button.setFlat(True)

        self.horizontalLayout_3.addWidget(self.test_button)


        self.verticalLayout.addLayout(self.horizontalLayout_3)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 900, 26))
        self.menubar.setFont(font)
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(False)
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuDevice = QMenu(self.menubar)
        self.menuDevice.setObjectName(u"menuDevice")
        self.menuSetting = QMenu(self.menubar)
        self.menuSetting.setObjectName(u"menuSetting")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
#if QT_CONFIG(shortcut)
        self.usb_label.setBuddy(self.test_button)
#endif // QT_CONFIG(shortcut)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDevice.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionConnect)
        self.menuFile.addAction(self.actionLogout)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit_2)
        self.menuDevice.addAction(self.actionEAX300)
        self.menuDevice.addSeparator()
        self.menuDevice.addAction(self.actionEAX500)
        self.menuDevice.addAction(self.actionEAX503)
        self.menuDevice.addAction(self.actionEAX504)
        self.menuDevice.addAction(self.actionEAX505)
        self.menuDevice.addAction(self.actionEAX510)
        self.menuDevice.addAction(self.actionEAX513)
        self.menuDevice.addAction(self.actionEAX514)
        self.menuDevice.addAction(self.actionEAX515)
        self.menuDevice.addAction(self.actionEAX520)
        self.menuDevice.addAction(self.actionEAX523)
        self.menuDevice.addAction(self.actionEAX524)
        self.menuDevice.addAction(self.actionEAX525)
        self.menuSetting.addAction(self.actionChange_font)
        self.menuSetting.addAction(self.actionModify_Settings)
        self.menuSetting.addSeparator()
        self.menuSetting.addAction(self.actionAdd_User)
        self.menuSetting.addAction(self.actionRemove_User)
        self.menuSetting.addSeparator()
        self.menuSetting.addAction(self.actionManual_Control)
        self.menuSetting.addAction(self.actionChip_Select)
        self.menuSetting.addSeparator()
        self.menuSetting.addAction(self.actionUpdate_Firmware)
        self.menuSetting.addAction(self.actionExplore_Directory)
        self.menuHelp.addAction(self.actionShow_Logs)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionHelp)

        self.retranslateUi(MainWindow)
        self.actionExit_2.triggered.connect(MainWindow.close)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"EAX Interface", None))
        self.actionConnect.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
#if QT_CONFIG(tooltip)
        self.actionConnect.setToolTip(QCoreApplication.translate("MainWindow", u"Connect to the fixture.", None))
#endif // QT_CONFIG(tooltip)
        self.actionLogout.setText(QCoreApplication.translate("MainWindow", u"Logout", None))
        self.actionExit_2.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
#if QT_CONFIG(shortcut)
        self.actionExit_2.setShortcut(QCoreApplication.translate("MainWindow", u"Esc", None))
#endif // QT_CONFIG(shortcut)
        self.actionEAX300.setText(QCoreApplication.translate("MainWindow", u"EAX300", None))
        self.actionEAX500.setText(QCoreApplication.translate("MainWindow", u"EAX500", None))
        self.actionEAX503.setText(QCoreApplication.translate("MainWindow", u"EAX503", None))
        self.actionEAX504.setText(QCoreApplication.translate("MainWindow", u"EAX504", None))
        self.actionEAX505.setText(QCoreApplication.translate("MainWindow", u"EAX505", None))
        self.actionEAX510.setText(QCoreApplication.translate("MainWindow", u"EAX510", None))
        self.actionEAX513.setText(QCoreApplication.translate("MainWindow", u"EAX513", None))
        self.actionEAX514.setText(QCoreApplication.translate("MainWindow", u"EAX514", None))
        self.actionEAX515.setText(QCoreApplication.translate("MainWindow", u"EAX515", None))
        self.actionEAX520.setText(QCoreApplication.translate("MainWindow", u"EAX520", None))
        self.actionEAX523.setText(QCoreApplication.translate("MainWindow", u"EAX523", None))
        self.actionEAX524.setText(QCoreApplication.translate("MainWindow", u"EAX524", None))
        self.actionEAX525.setText(QCoreApplication.translate("MainWindow", u"EAX525", None))
        self.actionChange_font.setText(QCoreApplication.translate("MainWindow", u"Change Font", None))
        self.actionModify_Settings.setText(QCoreApplication.translate("MainWindow", u"Modify Settings", None))
        self.actionAdd_User.setText(QCoreApplication.translate("MainWindow", u"Add User", None))
        self.actionRemove_User.setText(QCoreApplication.translate("MainWindow", u"Remove User", None))
        self.actionShow_Logs.setText(QCoreApplication.translate("MainWindow", u"Show Logs", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionManual_Control.setText(QCoreApplication.translate("MainWindow", u"Manual Control", None))
        self.actionChip_Select.setText(QCoreApplication.translate("MainWindow", u"Chip Select", None))
        self.actionUpdate_Firmware.setText(QCoreApplication.translate("MainWindow", u"Update Firmware", None))
        self.actionExplore_Directory.setText(QCoreApplication.translate("MainWindow", u"Explore Directory", None))
        self.actionHelp.setText(QCoreApplication.translate("MainWindow", u"Help", None))
        self.text_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Text Area", None))
        self.program_button.setText("")
#if QT_CONFIG(shortcut)
        self.program_button.setShortcut(QCoreApplication.translate("MainWindow", u"P", None))
#endif // QT_CONFIG(shortcut)
        self.groupBox_2.setTitle("")
        self.device_label.setText("")
        self.groupBox.setTitle("")
        self.label_usb_icon.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><img width=\"52\" height=\"52\" src=\":/resources/icons/images/icons/disconnected2.png\"/></p></body></html>", None))
        self.usb_label.setText(QCoreApplication.translate("MainWindow", u"USB: Not Connected", None))
        self.test_button.setText("")
#if QT_CONFIG(shortcut)
        self.test_button.setShortcut(QCoreApplication.translate("MainWindow", u"T", None))
#endif // QT_CONFIG(shortcut)
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuDevice.setTitle(QCoreApplication.translate("MainWindow", u"Device", None))
        self.menuSetting.setTitle(QCoreApplication.translate("MainWindow", u"Setting", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
    # retranslateUi

