
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-04T11:59:26+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9d4e883b1286af0d3043ae21ecaa0802709b3296",
 "version": "0.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
