# Copyright 2022 OpenSynergy Indonesia
# Copyright 2022 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl-3.0-standalone.html).

from . import (
    accountant_business_process,
    accountant_general_audit,
    accountant_relevant_regulation,
    accountant_financial_report_preparation,
    accountant_fraud_factor,
    ws_ra150,
    ws_ra1501,
    ws_ra1502,
    ws_ra1503,
    ws_ra1503_business_process,
    ws_ra1503_expert,
    ws_ra1503_other_significant_information,
    ws_ra1503_previous_significant_information,
    ws_ra1504,
    ws_ra1504_relevant_regulation,
    ws_ra1504_relevant_regulation_account,
    ws_ra1505,
    ws_ra1505_economic_business_environment,
    ws_ra1505_energy_business_environment,
    ws_ra1505_ifrs_business_environment,
    ws_ra1505_natural_business_environment,
    ws_ra1505_regulation_business_environment,
    ws_ra1505_technology_business_environment,
    ws_ra1505_trend_business_environment,
    ws_ra1506,
    ws_ra1507,
    ws_ra1507_financial_report_preparation,
    ws_ra1508,
    ws_ra1508_opportunity_fraud_factor,
    ws_ra1508_preassure_fraud_factor,
    ws_ra1508_rationalization_fraud_factor,
    accountant_general_audit_standard_detail,
)
