"""
    Invision Community API Schema

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import invision_client
from invision_client.model.forum import Forum
from invision_client.model.poll import Poll
from invision_client.model.post import Post
globals()['Forum'] = Forum
globals()['Poll'] = Poll
globals()['Post'] = Post
from invision_client.model.topic import Topic


class TestTopic(unittest.TestCase):
    """Topic unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTopic(self):
        """Test Topic"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Topic()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
