"""
    Invision Community API Schema

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import invision_client
from invision_client.model.forum import Forum
globals()['Forum'] = Forum
from invision_client.model.forums_forums_get200_response import ForumsForumsGet200Response


class TestForumsForumsGet200Response(unittest.TestCase):
    """ForumsForumsGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testForumsForumsGet200Response(self):
        """Test ForumsForumsGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ForumsForumsGet200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
