# coding: utf-8

"""
    Cashfree LRS

    CashFree LRS APIs (v2)  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: nextgenapi@cashfree.com
    Generated by: https://openapi-generator.tech
"""

from cashfree_lrs_client.paths.orders_documents_upload.post import BulkDocumentsUpload
from cashfree_lrs_client.paths.beneficiaries.post import CreateBeneficiary
from cashfree_lrs_client.paths.orders.post import CreateOrder
from cashfree_lrs_client.paths.remitters.post import CreateRemitter
from cashfree_lrs_client.paths.fx_rate_details.post import FetchForexRate
from cashfree_lrs_client.paths.orders_order_id_process.post import ProcessOrder
from cashfree_lrs_client.paths.webhooks.post import SetupWebhooks
from cashfree_lrs_client.paths.orders_order_id_documents_upload.post import UploadDocuments


class LrsApi(
    BulkDocumentsUpload,
    CreateBeneficiary,
    CreateOrder,
    CreateRemitter,
    FetchForexRate,
    ProcessOrder,
    SetupWebhooks,
    UploadDocuments,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
