
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-08T11:33:35+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b709118a1b58c4d7222616531b43c5e68b6945bf",
 "version": "0.8.0.post.dev8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
