
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-08T06:30:08+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7e3cdc2b5a254174f5ec51dc54362b7e41da3bb1",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
