
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-03T21:57:15-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "23a53a39ccc31fb9389fd43b3027c4525c1e0383",
 "version": "v0.0.35"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
