# Generated by Django 4.2 on 2023-07-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_silly_stripe', '0004_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
