# Generated by Django 4.2 on 2023-07-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_silly_stripe', '0009_subscription_end_time_subscription_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_time',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_time',
            field=models.CharField(max_length=32),
        ),
    ]
