
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-05T19:47:37+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "243fb79307206d4c63f1b75e0713a432d6fca513",
 "version": "2.0.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
