# Generated by Django 3.2.12 on 2022-02-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paweljong', '0002_event_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='feedback_aspects',
            field=models.ManyToManyField(blank=True, null=True, related_name='event', to='paweljong.FeedbackAspect', verbose_name='Feedback aspects'),
        ),
    ]
