# Generated by Django 3.2.12 on 2022-02-16 18:52

import ckeditor.fields
from django.db import migrations
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('paweljong', '0003_alter_event_feedback_aspects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='website',
        ),
        migrations.AddField(
            model_name='event',
            name='information',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Information about the event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='iban',
            field=localflavor.generic.models.IBANField(blank=True, max_length=34, null=True, verbose_name='IBAN (for SEPA direct debit)'),
        ),
    ]
