# Generated by Django 3.2.12 on 2022-02-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paweljong', '0004_richtext_field_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='medical_information',
            field=models.TextField(blank=True, default='', verbose_name='Medical information / intolerances'),
        ),
    ]
