# Generated by Django 3.2.12 on 2022-02-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paweljong', '0005_eventregistration_medical_information'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'verbose_name': 'Event registration', 'verbose_name_plural': 'Event registrations'},
        ),
        migrations.AddConstraint(
            model_name='eventfeedback',
            constraint=models.UniqueConstraint(fields=('person', 'event'), name='unique_person_feedback_per_event'),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(fields=('person', 'event'), name='unique_person_registration_per_event'),
        ),
    ]
