# Generated by Django 3.2.12 on 2022-02-20 15:24

import ckeditor.fields
import aleksis.core.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('paweljong', '0006_unique_constraints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='channel',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='school',
            field=models.CharField(default='', max_length=255, verbose_name='Name of school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='school_class',
            field=models.CharField(default='', max_length=255, verbose_name='School class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='school_place',
            field=models.CharField(default='', max_length=255, verbose_name='Place of the school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='feedback_aspects',
            field=models.ManyToManyField(blank=True, related_name='event', to='paweljong.FeedbackAspect', verbose_name='Feedback aspects'),
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_data', models.JSONField(default=dict, editable=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('term', ckeditor.fields.RichTextField(verbose_name='Term')),
                ('site', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', aleksis.core.managers.AlekSISBaseManager()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='terms',
            field=models.ManyToManyField(blank=True, related_name='event', to='paweljong.Terms', verbose_name='Terms'),
        ),
    ]
