# Generated by Django 3.2.12 on 2022-02-20 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paweljong', '0007_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='accept_data',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='accept_general_terms',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='accept_terms',
        ),
    ]
