# Generated by Django 3.2.12 on 2022-02-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paweljong', '0009_remove_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='confirmation_text',
            field=models.TextField(default='', verbose_name='Confirmation text'),
            preserve_default=False,
        ),
    ]
