# Generated by Django 3.2.12 on 2022-02-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paweljong', '0010_term_confirmation_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='accepted_terms',
            field=models.ManyToManyField(related_name='registrations', to='paweljong.Terms', verbose_name='Accepted terms'),
        ),
    ]
