# Generated by Django 3.2.12 on 2022-02-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paweljong', '0011_registration_accepted_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Slug', blank=True),
            preserve_default=False,
        ),
    ]
