# Generated by Django 3.2.12 on 2022-03-01 15:19

import ckeditor.fields
import aleksis.core.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_preference_model_unique'),
        ('sites', '0002_alter_domain_unique'),
        ('paweljong', '0012_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='paweljong.event', verbose_name='Event'),
        ),
        migrations.CreateModel(
            name='InfoMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_data', models.JSONField(default=dict, editable=False)),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Text')),
                ('reply_to', models.EmailField(blank=True, max_length=254, verbose_name='Request replies to')),
                ('active', models.BooleanField(default=False, verbose_name='Mailing is active')),
                ('sender', models.EmailField(blank=True, max_length=254, verbose_name='Sender')),
                ('send_to_person', models.BooleanField(default=True, verbose_name='Send to registered person')),
                ('send_to_guardians', models.BooleanField(default=False, verbose_name='Send to guardians')),
                ('sent_to', models.ManyToManyField(blank=True, editable=False, related_name='received_info_mailings', to='core.Person', verbose_name='Sent to persons')),
                ('site', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', aleksis.core.managers.AlekSISBaseManager()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='info_mailings',
            field=models.ManyToManyField(blank=True, related_name='events', to='paweljong.InfoMailing', verbose_name='Info mailings'),
        ),
    ]
