# Generated by Django 3.2.12 on 2022-03-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paweljong', '0015_registrationstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='states',
            field=models.ManyToManyField(related_name='registrations', to='paweljong.RegistrationState', verbose_name='States'),
        ),
    ]
