# Generated by Django 3.2.12 on 2022-03-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paweljong', '0016_eventregistration_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
