# Generated by Django 3.2.13 on 2022-06-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paweljong', '0018_payment_with_tezor'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='retracted',
            field=models.BooleanField(default=False, verbose_name='Retracted'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='retracted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Retracted at'),
        ),
    ]
