# Generated by Django 3.2.13 on 2022-06-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paweljong', '0019_retractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='checked_in',
            field=models.BooleanField(default=False, verbose_name='Checked in'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='checked_in_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Checked in at'),
        ),
    ]
