# Generated by Django 3.2.13 on 2022-06-24 18:31

import aleksis.core.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0041_update_gender_choices'),
        ('paweljong', '0020_check_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationstate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_data', models.JSONField(default=dict, editable=False)),
                ('comment', models.CharField(max_length=60, verbose_name='Comment')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of check')),
                ('lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude of check')),
                ('lon', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude of check')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='paweljong.event', verbose_name='Related event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_checkpoints', to='core.person', verbose_name='Checked person')),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_checkpoints_created', to='core.person', verbose_name='Checked by person')),
                ('site', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', aleksis.core.managers.AlekSISBaseManager()),
            ],
        ),
    ]
