# Generated by Django 3.2.13 on 2022-07-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paweljong', '0021_checkpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomailing',
            name='send_to_not_checked_in',
            field=models.BooleanField(default=True, verbose_name='Send to participants who did not check in'),
        ),
        migrations.AddField(
            model_name='infomailing',
            name='send_to_retracted',
            field=models.BooleanField(default=False, verbose_name='Send to participants who retracted'),
        ),
    ]
