# Generated by Django 3.2.19 on 2023-06-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paweljong', '0022_send_to_retracted_or_not_checked_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cost in €'),
        ),
    ]
