# Generated by Django 3.2.19 on 2023-06-04 14:54

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('paweljong', '0023_eventregistration_cost'),
    ]

    operations = [
        migrations.RunSQL("UPDATE paweljong_eventregistration SET cost = (SELECT paweljong_event.cost FROM paweljong_event WHERE paweljong_event.id = paweljong_eventregistration.event_id);")
    ]
