
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-04T20:05:48-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "55ba98114edc6cbc61f6052d1f5e9e6789ff644a",
 "version": "2023.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
