# This file automatically generated by
#    /Users/couchbase/jenkins/workspace/python/sdk/python-packaging-pipeline/py-client/./couchbase_version.py
# at
#    2023-08-08 13:49:08.923809
__version__ = '4.1.7'