# coding: utf-8

"""
    Cashfree LRS

    CashFree LRS APIs (v2)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: nextgenapi@cashfree.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import cashfree_lrs_client
from cashfree_lrs_client.models.create_order_response import CreateOrderResponse  # noqa: E501
from cashfree_lrs_client.rest import ApiException

class TestCreateOrderResponse(unittest.TestCase):
    """CreateOrderResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateOrderResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOrderResponse`
        """
        model = cashfree_lrs_client.models.create_order_response.CreateOrderResponse()  # noqa: E501
        if include_optional :
            return CreateOrderResponse(
                tcs = 0, 
                gst = 0, 
                fx_rate = 0, 
                amount_to_pay = 0, 
                handling_charges = 0, 
                order_expiry_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                payment_link = '', 
                order_token = '', 
                missing_documents = [
                    ''
                    ]
            )
        else :
            return CreateOrderResponse(
        )
        """

    def testCreateOrderResponse(self):
        """Test CreateOrderResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
