# coding: utf-8

"""
    Cashfree LRS

    CashFree LRS APIs (v2)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: nextgenapi@cashfree.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import cashfree_lrs_client
from cashfree_lrs_client.api.lrs_api import LrsApi  # noqa: E501
from cashfree_lrs_client.rest import ApiException


class TestLrsApi(unittest.TestCase):
    """LrsApi unit test stubs"""

    def setUp(self):
        self.api = cashfree_lrs_client.api.lrs_api.LrsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bulk_documents_upload(self):
        """Test case for bulk_documents_upload

        Upload Documents in Bulk  # noqa: E501
        """
        pass

    def test_create_beneficiary(self):
        """Test case for create_beneficiary

        Create Beneficiary  # noqa: E501
        """
        pass

    def test_create_order(self):
        """Test case for create_order

        Create LRS Order  # noqa: E501
        """
        pass

    def test_create_remitter(self):
        """Test case for create_remitter

        Create Remitter  # noqa: E501
        """
        pass

    def test_fetch_forex_rate(self):
        """Test case for fetch_forex_rate

        Fetch FX Rate  # noqa: E501
        """
        pass

    def test_process_order(self):
        """Test case for process_order

        Process Order  # noqa: E501
        """
        pass

    def test_setup_webhooks(self):
        """Test case for setup_webhooks

        Setup Webhooks  # noqa: E501
        """
        pass

    def test_upload_documents(self):
        """Test case for upload_documents

        Upload Documents  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
