# coding: utf-8

"""
    Cashfree LRS

    CashFree LRS APIs (v2)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: nextgenapi@cashfree.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import cashfree_lrs_client
from cashfree_lrs_client.models.create_beneficiary_request import CreateBeneficiaryRequest  # noqa: E501
from cashfree_lrs_client.rest import ApiException

class TestCreateBeneficiaryRequest(unittest.TestCase):
    """CreateBeneficiaryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateBeneficiaryRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateBeneficiaryRequest`
        """
        model = cashfree_lrs_client.models.create_beneficiary_request.CreateBeneficiaryRequest()  # noqa: E501
        if include_optional :
            return CreateBeneficiaryRequest(
                beneficiary_id = '0', 
                account_holder_name = '012', 
                account_number = '012345678', 
                swift_code = '01234567', 
                iban = '01234567891011121314151617', 
                routing_number = '012345678', 
                bank_name = '012', 
                bank_address = '012', 
                bank_country = '01', 
                sort_code = '0', 
                transit_code = '01234', 
                bsb_number = '012345', 
                address = '012', 
                city = '012', 
                state = '012', 
                country = '01', 
                postal_code = '0'
            )
        else :
            return CreateBeneficiaryRequest(
                beneficiary_id = '0',
                account_holder_name = '012',
                account_number = '012345678',
                swift_code = '01234567',
                bank_name = '012',
                bank_address = '012',
                bank_country = '01',
                address = '012',
                city = '012',
                state = '012',
                country = '01',
                postal_code = '0',
        )
        """

    def testCreateBeneficiaryRequest(self):
        """Test CreateBeneficiaryRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
