
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-27T12:18:17+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5358d036abb5a90120d7943e7079dac9e2998f39",
 "version": "1.3rc0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
