
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-04T10:08:24-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "bd0af3474fb4b6306c749a194b350199cd332a49",
 "version": "v0.3.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
