
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-08T20:56:49+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "893a1f86c0bbc41bae0574def4a5f5c2d5355e26",
 "version": "2023.08.08post0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
