booster = {
      "absolutely": 1,
      "completely": 1,
      "ought": -1,
      "could": -1,
      "definitely": 1,
      "especially": 1,
      "extremely": 1,
      "fuckin": 1,
      "fucking": 1,
      "hugely": 1,
      "incredibly": 1,
      "just": -1,
      "might": -1,
      "ought": -1,
      "overwhelmingly": 1,
      "really": 1,
      "should": -1,
      "slightly": -1,
      "sometimes": -1,
      "total": 1,
      "totally": 1,
      "very": 1,
      "would": -1
    }