# coding: utf-8

"""
    Cashfree LRS

    CashFree LRS APIs (v2)  # noqa: E501

    The version of the OpenAPI document: 1.0.17
    Contact: nextgenapi@cashfree.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class Country(str, Enum):
    """
    Allowed values for Country. Catered to Swadesh's use case.
    """

    """
    allowed enum values
    """
    US = 'US'
    IN = 'IN'

    @classmethod
    def from_json(cls, json_str: str) -> Country:
        """Create an instance of Country from a JSON string"""
        return Country(json.loads(json_str))


