
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-08T12:09:11+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6a6ab560ecb18fdc7f5efe362cc542fe769c787f",
 "version": "0.8.0.post.dev14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
