
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-03T12:31:05+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "95fc6a6986bc48d9b4e8f9cffa6f80737e52e617",
 "version": "v0.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
