# coding: utf-8

"""
    Cashfree LRS

    CashFree LRS APIs (v2)  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: nextgenapi@cashfree.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from cashfree_lrs_client import schemas  # noqa: F401


class FetchForexRateRequest(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "to_amount",
            "purpose",
            "to_currency",
        }
        
        class properties:
        
            @staticmethod
            def to_currency() -> typing.Type['Currency']:
                return Currency
            to_amount = schemas.Float64Schema
        
            @staticmethod
            def purpose() -> typing.Type['Purpose']:
                return Purpose
            
            
            class remitter_id(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 50
                    min_length = 3
            customer_declaration = schemas.Float64Schema
            education_loan = schemas.BoolSchema
            __annotations__ = {
                "to_currency": to_currency,
                "to_amount": to_amount,
                "purpose": purpose,
                "remitter_id": remitter_id,
                "customer_declaration": customer_declaration,
                "education_loan": education_loan,
            }
    
    to_amount: MetaOapg.properties.to_amount
    purpose: 'Purpose'
    to_currency: 'Currency'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["to_currency"]) -> 'Currency': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["to_amount"]) -> MetaOapg.properties.to_amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["purpose"]) -> 'Purpose': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["remitter_id"]) -> MetaOapg.properties.remitter_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["customer_declaration"]) -> MetaOapg.properties.customer_declaration: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["education_loan"]) -> MetaOapg.properties.education_loan: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["to_currency", "to_amount", "purpose", "remitter_id", "customer_declaration", "education_loan", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["to_currency"]) -> 'Currency': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["to_amount"]) -> MetaOapg.properties.to_amount: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["purpose"]) -> 'Purpose': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["remitter_id"]) -> typing.Union[MetaOapg.properties.remitter_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["customer_declaration"]) -> typing.Union[MetaOapg.properties.customer_declaration, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["education_loan"]) -> typing.Union[MetaOapg.properties.education_loan, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["to_currency", "to_amount", "purpose", "remitter_id", "customer_declaration", "education_loan", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        to_amount: typing.Union[MetaOapg.properties.to_amount, decimal.Decimal, int, float, ],
        purpose: 'Purpose',
        to_currency: 'Currency',
        remitter_id: typing.Union[MetaOapg.properties.remitter_id, str, schemas.Unset] = schemas.unset,
        customer_declaration: typing.Union[MetaOapg.properties.customer_declaration, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        education_loan: typing.Union[MetaOapg.properties.education_loan, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'FetchForexRateRequest':
        return super().__new__(
            cls,
            *_args,
            to_amount=to_amount,
            purpose=purpose,
            to_currency=to_currency,
            remitter_id=remitter_id,
            customer_declaration=customer_declaration,
            education_loan=education_loan,
            _configuration=_configuration,
            **kwargs,
        )

from cashfree_lrs_client.model.currency import Currency
from cashfree_lrs_client.model.purpose import Purpose
