# Generated by Django 4.0.6 on 2022-07-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lxp', '0004_quizattempt_session_key_alter_quizattempt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='navbar',
            field=models.BooleanField(default=True, help_text='Show side navbar for this course?'),
        ),
    ]
