# Generated by Django 4.1 on 2022-09-12 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lxp", "0006_alter_academypage_body_alter_activitypage_body_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LXPSettings",
        ),
    ]
