
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-08T11:40:57+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a554e63ed281e46b5bda8b88dedd61870907438a",
 "version": "0.8.0.post.dev10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
