# Copyright (c) 2022-2023 IO-Aero. All rights reserved. Use of this
# source code is governed by the IO-Aero License, that can
# be found in the LICENSE.md file.

"""Module stub file."""

def initialise_logger() -> None: ...
def prepare_latitude(latitude_string: str) -> str: ...
def prepare_longitude(longitude_string: str) -> str: ...
def progress_msg(msg: str) -> None: ...
def progress_msg_core(msg: str) -> None: ...
def progress_msg_time_elapsed(duration: int, event: str) -> None: ...
def terminate_fatal(error_msg: str) -> None: ...
