
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-07T11:11:18+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "91e361fff171fb6d83ac0ee07fe8573352a7ecf2",
 "version": "5.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
