
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-07T14:39:59-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "86ce6a967a0989096cc88e2e5e78debb8a698da0",
 "version": "5.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
