
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-03T16:56:34-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "17b96b1c1b95625e799c5b550cd4e34e33615dc5",
 "version": "0.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
