
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-08T22:53:30+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4952e93af36ff5755f991278bcd34e2a707d7072",
 "version": "v0.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
