# Generated by Django 4.2.1 on 2023-08-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cid',
            name='attrs',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='oid',
            name='attrs',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='pid',
            name='attrs',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='tid',
            name='attrs',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='uid',
            name='attrs',
            field=models.JSONField(default=dict),
        ),
    ]
