# Generated by Django 4.1.7 on 2023-03-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountconfig',
            old_name='deletedViaCascade',
            new_name='deleted_via_cascade',
        ),
        migrations.RenameField(
            model_name='accountingentry',
            old_name='deletedViaCascade',
            new_name='deleted_via_cascade',
        ),
        migrations.RenameField(
            model_name='biller',
            old_name='deletedViaCascade',
            new_name='deleted_via_cascade',
        ),
        migrations.RenameField(
            model_name='billerfield',
            old_name='deletedViaCascade',
            new_name='deleted_via_cascade',
        ),
        migrations.RenameField(
            model_name='billerfield',
            old_name='valiation_field',
            new_name='validation_field',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='deletedViaCascade',
            new_name='deleted_via_cascade',
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='deletedViaCascade',
            new_name='deleted_via_cascade',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='deletedViaCascade',
            new_name='deleted_via_cascade',
        ),
        migrations.RenameField(
            model_name='feeaccountconfig',
            old_name='deletedViaCascade',
            new_name='deleted_via_cascade',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='deletedViaCascade',
            new_name='deleted_via_cascade',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='deletedViaCascade',
            new_name='deleted_via_cascade',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='deletedViaCascade',
            new_name='deleted_via_cascade',
        ),
        migrations.RemoveField(
            model_name='accountconfig',
            name='deletedAt',
        ),
        migrations.RemoveField(
            model_name='accountingentry',
            name='deletedAt',
        ),
        migrations.RemoveField(
            model_name='biller',
            name='deletedAt',
        ),
        migrations.RemoveField(
            model_name='billerfield',
            name='deletedAt',
        ),
        migrations.RemoveField(
            model_name='category',
            name='deletedAt',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='deletedAt',
        ),
        migrations.RemoveField(
            model_name='country',
            name='deletedAt',
        ),
        migrations.RemoveField(
            model_name='feeaccountconfig',
            name='deletedAt',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='deletedAt',
        ),
        migrations.RemoveField(
            model_name='request',
            name='deletedAt',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deletedAt',
        ),
        migrations.AlterField(
            model_name='accountconfig',
            name='deleted_by_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='deleted_by_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='biller',
            name='deleted_by_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='billerfield',
            name='deleted_by_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='deleted_by_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='deleted_by_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='deleted_by_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feeaccountconfig',
            name='deleted_by_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='deleted_by_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='deleted_by_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_by_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
