# Generated by Django 4.2 on 2023-05-18 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_accountingentry_fees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingentry',
            name='settlement_account',
        ),
        migrations.AddField(
            model_name='billerform',
            name='settlement_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.accountconfig'),
            preserve_default=False,
        ),
    ]
