
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-08T17:41:52-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b38968f9a0982ba5c9130804e248ac68c7a3acca",
 "version": "5.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
