# coding: utf-8
# file generated by setuptools_scm + setup.py
# don't change, don't track in version control
git_hash = b',\x88\x18"'
full_git_hash = '2c881822f6cf7b63f63194a1acb4021f8b2bd36b'
git_branch = 'HEAD'
dirty = False
