# Generated by Django 3.2.12 on 2022-04-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lxp', '0002_lxpwebpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['sort_order'], 'verbose_name': 'Learning Topic', 'verbose_name_plural': 'Learning Topics'},
        ),
        migrations.AddField(
            model_name='topic',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
