# Generated by Django 4.1.10 on 2023-08-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("lxp", "0008_alter_academypage_body_alter_activitypage_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursepage",
            name="security_group",
            field=models.ManyToManyField(blank=True, to="auth.group"),
        ),
        migrations.AlterField(
            model_name="coursepage",
            name="security",
            field=models.IntegerField(
                choices=[
                    (0, "Full guest access"),
                    (1, "Quizzes require login"),
                    (2, "Downloads require login"),
                    (4, "Course content requires login"),
                    (8, "Content list requires login"),
                    (16, "Course hidden from non-logged"),
                    (32, "Course hidden from user not in specific groups"),
                    (64, "Course hidden from non-enrolled"),
                ],
                default=0,
            ),
        ),
    ]
