
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-08T09:55:12-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "4fb17cdb996bbb693c5814d2a7bb3c13771816a8",
 "version": "2.5.52"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
